### ISSUE TITLE
Facebook shop not support not english product names

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/facebook-shop#1]
my product name is Продукт
when i open it in Facebook shop, link is mystore.com/Продукт
and show error

**Comment by DmitriyKulagin** [comment]
The links use the SEO attribute "Search engine friendly page name". If you fill it correctly, the error is not reproduced.

**Comment by DmitriyKulagin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Обновить до 4.10 facebook-shop plugin](https://trello.com/c/p5YyxBp7/408-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C-%D0%B4%D0%BE-410-facebook-shop-plugin)
