### ISSUE TITLE
Ptoduct name link is not working in Facebook

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/facebook-shop#2]
When we click in product picture or details button, product details page open in new tab, but when we click on product name link, show Error`
Refused to display 'https://store.com/product-name' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by DmitriyKulagin** [comment]
Hi, @tigran-avdalyan 
what version of the plugin are you using?

**Comment by DmitriyKulagin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Обновить до 4.10 facebook-shop plugin](https://trello.com/c/p5YyxBp7/408-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C-%D0%B4%D0%BE-410-facebook-shop-plugin)

**Comment by DmitriyKulagin** [comment]
Not reproduced.

**Comment by tigran-avdalyan** [comment]
@DmitriyKulagin @skoshelev 
Version: 1.41
![aa](https://user-images.githubusercontent.com/17789934/44366648-63de2d00-a4de-11e8-97b0-7320dada0592.gif)

**Comment by tigran-avdalyan** [comment]
@DmitriyKulagin 
issue because name link not have parameter 
target="_blank"
